all:
	@cd adi_ascii && $(MAKE)
	@cd ART && $(MAKE)
	@cd cfs && $(MAKE)
	@cd ctg_rasch && $(MAKE)
	@cd ctg_sonicaid && $(MAKE)
	@cd dadisp && $(MAKE)
	@cd dasylab && $(MAKE)
	@cd edf && $(MAKE)
	@cd ishne && $(MAKE)
	@cd ideeq_ascii && $(MAKE)
	@cd mit_bih && $(MAKE)
	@cd mortara_sparc && $(MAKE)
	@cd portapres && $(MAKE)
	@cd portilab && $(MAKE)
	@cd read_rri && $(MAKE)

clean:
	@cd adi_ascii && $(MAKE) clean
	@cd ART && $(MAKE) clean
	@cd cfs && $(MAKE) clean
	@cd ctg_rasch && $(MAKE) clean
	@cd ctg_sonicaid && $(MAKE) clean
	@cd dadisp && $(MAKE) clean
	@cd dasylab && $(MAKE) clean
	@cd edf && $(MAKE) clean
	@cd ishne && $(MAKE) clean
	@cd ideeq_ascii && $(MAKE) clean
	@cd mit_bih && $(MAKE) clean
	@cd mortara_sparc && $(MAKE) clean
	@cd portapres && $(MAKE) clean
	@cd portilab && $(MAKE) clean
	@cd read_rri && $(MAKE) clean

distclean: clean

