######################################################################
# Automatically generated by qmake (2.01a) Sa Okt 7 12:27:49 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_main.cpp
