all:
	@cd shared && $(MAKE)
	@cd ts_view && $(MAKE)
	@cd annot_comment_view && $(MAKE)
	@cd ch_sel_dlg && $(MAKE)
	@cd cont_ap_view && $(MAKE)
	@cd ctg_view && $(MAKE)
	@cd ecg_view && $(MAKE)
	@cd eval_dlg && $(MAKE)
	@cd ev_summary_view && $(MAKE)
	@cd plot_view && $(MAKE)
	@cd plugin_info_dlg && $(MAKE)
	@cd ra_view && $(MAKE)
	@cd sig_sel_dlg && $(MAKE)
	@cd simple_calc_dlg && $(MAKE)

clean:
	@cd shared && $(MAKE) clean
	@cd ts_view && $(MAKE) clean
	@cd annot_comment_view && $(MAKE) clean
	@cd ch_sel_dlg && $(MAKE) clean
	@cd cont_ap_view && $(MAKE) clean
	@cd ctg_view && $(MAKE) clean
	@cd ecg_view && $(MAKE) clean
	@cd eval_dlg && $(MAKE) clean
	@cd ev_summary_view && $(MAKE) clean
	@cd plot_view && $(MAKE) clean
	@cd plugin_info_dlg && $(MAKE) clean
	@cd ra_view && $(MAKE) clean
	@cd sig_sel_dlg && $(MAKE) clean
	@cd simple_calc_dlg && $(MAKE) clean

distclean:
	- @cd shared && $(MAKE) distclean
	- @cd ts_view && $(MAKE) distclean
	- @cd annot_comment_view && $(MAKE) distclean
	- @cd ch_sel_dlg && $(MAKE) distclean
	- @cd cont_ap_view && $(MAKE) distclean
	- @cd ctg_view && $(MAKE) distclean
	- @cd ecg_view && $(MAKE) distclean
	- @cd eval_dlg && $(MAKE) distclean
	- @cd ev_summary_view && $(MAKE) distclean
	- @cd plot_view && $(MAKE) distclean
	- @cd plugin_info_dlg && $(MAKE) distclean
	- @cd ra_view && $(MAKE) distclean
	- @cd sig_sel_dlg && $(MAKE) distclean
	- @cd simple_calc_dlg && $(MAKE) distclean

