all:
	@cd view && $(MAKE)
	@cd access && $(MAKE)
	@cd process && $(MAKE)

clean:
	@cd view && $(MAKE) clean
	@cd access && $(MAKE) clean
	@cd process && $(MAKE) clean

distclean:
	- @cd view && $(MAKE) distclean
	- @cd access && $(MAKE) distclean
	- @cd process && $(MAKE) distclean

