// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
librasch_sci_path=get_file_path('loader.sce');
functions=[ 'ra_scilab';
];
addinter(librasch_sci_path+'/librasch_sci.so','librasch_sci',functions);
