all:
	@cd ap_morphology && $(MAKE)
	@cd calibration && $(MAKE)
	@cd dawes_redman && $(MAKE)
	@cd detect_ctg && $(MAKE)
	@cd detect_ecg && $(MAKE)
	@cd ecg && $(MAKE)
	@cd fiducial_point && $(MAKE)
	@cd freq_analysis && $(MAKE)
	@cd hrv && $(MAKE)
	@cd ra_template && $(MAKE)
	@cd respiration && $(MAKE)

clean:
	@cd ap_morphology && $(MAKE) clean
	@cd calibration && $(MAKE) clean
	@cd dawes_redman && $(MAKE) clean
	@cd detect_ctg && $(MAKE) clean
	@cd detect_ecg && $(MAKE) clean
	@cd ecg && $(MAKE) clean
	@cd fiducial_point && $(MAKE) clean
	@cd freq_analysis && $(MAKE) clean
	@cd hrv && $(MAKE) clean
	@cd ra_template && $(MAKE) clean
	@cd respiration && $(MAKE) clean

distclean: clean

